version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["A2-insubstantial", "B0-silent", "C1-low 📌"]
    # Update Substrate & Polkadot only
    allow:
      - dependency-name: "polkadot-primitives"
    schedule:
      interval: "daily"
