[package]
name = "cumulus-pallet-xcmp-queue"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
# Other dependencies
codec = { package = "parity-scale-codec", version = "2.3.0", features = [ "derive" ], default-features = false }
rand_chacha = { version = "0.3.0", default-features = false }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }
log = { version = "0.4.14", default-features = false }

# Substrate Dependencies
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "kiz-temp" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "kiz-temp" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "kiz-temp" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "kiz-temp" }

# Polkadot Dependencies
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "kiz-temp" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "kiz-temp" }

# Cumulus Dependencies
cumulus-primitives-core = { path = "../../primitives/core", default-features = false }

[dev-dependencies]
sp-core = { git = 'https://github.com/paritytech/substrate', branch = "kiz-temp" }
sp-io = { git = 'https://github.com/paritytech/substrate', branch = "kiz-temp" }
cumulus-pallet-parachain-system = { path = "../parachain-system" }
xcm-builder = { git = "https://github.com/paritytech/polkadot", branch = "kiz-temp" }
pallet-balances = { git = 'https://github.com/paritytech/substrate', branch = "kiz-temp" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"log/std",
	"scale-info/std",
	"sp-std/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"cumulus-primitives-core/std",
	"xcm/std",
	"xcm-executor/std",
]
